vim.keymap.set("n", "<leader>dg", ":diffget ", {})
vim.keymap.set("n", "<leader>dp", ":diffput ", {})
vim.keymap.set("n", "<leader>ga", ":Git add .<cr>", {})
vim.keymap.set("n", "<leader>gca", ":Git commit --amend<cr>", {})
vim.keymap.set("n", "<leader>gci", ":Git commit<cr>", {})
vim.keymap.set("n", "<leader>gcn", ":Git commit --amend --no-edit<cr>", {})
vim.keymap.set("n", "<leader>gcob", ":Git checkout -b ", {})
-- vim.keymap.set("n", "<leader>gd", ":Gdiff<cr>", {})
vim.keymap.set("n", "<leader>gft", ":Git fetch<cr>", {})
vim.keymap.set("n", "<leader>gi", ":Git ", {})
vim.keymap.set("n", "<leader>gl", ":Git log --oneline --all --decorate --graph<cr>", {})
vim.keymap.set("n", "<leader>gp", ":Git push<cr>", {})
vim.keymap.set("n", "<leader>grb", ":Git rebase origin ", {})
vim.keymap.set("n", "<leader>gre", ":Git reset --hard origin/", {})
vim.keymap.set("n", "<leader>gsa", ":Git stash<cr>", {})
vim.keymap.set("n", "<leader>gsp", ":Git stash pop<cr>", {})
vim.keymap.set("n", "<leader>gst", ":Git status<cr>", {})
vim.keymap.set("n", "<leader>gsw", ":Git switch ", {})
