vim.keymap.set("n", "<leader>ga", ":Git add .<cr>", {})
vim.keymap.set("n", "<leader>gcm", ":Git commit<cr>", {})
vim.keymap.set("n", "<leader>gci", ":Git commit --amend<cr>", {})
vim.keymap.set("n", "<leader>gcn", ":Git commit --amend --no-edit<cr>", {})
vim.keymap.set("n", "<leader>gcob", ":Git checkout -b ", {})
vim.keymap.set("n", "<leader>gf", ":Git fetch<cr>", {})
vim.keymap.set("n", "<leader>gl", ":Git log --oneline --all --decorate --graph<cr>", {})
