vim.keymap.set("n", "<leader>gi", vim.cmd.Git)
vim.keymap.set("n", "<leader>gs", ":Git st<cr>", {})
vim.keymap.set("n", "<leader>gl", ":Git lol<cr>", {})
vim.keymap.set("n", "<leader>ga", ":Git add .<cr>", {})
vim.keymap.set("n", "<leader>gci", ":Git commit<cr>", {})
vim.keymap.set("n", "<leader>gca", ":Git commit --amend<cr>", {})
vim.keymap.set("n", "<leader>gcn", ":Git commit --amend --no-edit<cr>", {})
vim.keymap.set("n", "<leader>gsw", ":Git switch ", {})
vim.keymap.set("n", "<leader>gcob", ":Git checkout -b ", {})
vim.keymap.set("n", "<leader>gp", ":Git push<cr>", {})
vim.keymap.set("n", "<leader>gd", ":Gdiff<cr>", {})
vim.keymap.set("n", "<leader>dg", ":diffget ", {})
vim.keymap.set("n", "<leader>dp", ":diffput ", {})

