# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  padding:
    x: 6
    y: 6

  dynamic_padding: false

  opacity: 1.0

  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty


scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

# Font configuration
font:
  normal:
    family: CaskaydiaCoveNerdFont

  bold:
    family: CaskaydiaCoveNerdFont
    style: Bold

  italic:
    family: CaskaydiaCoveNerdFont
    style: Italic

  bold_italic:
    family: CaskaydiaCoveNerdFont
    style: Bold Italic

  size: 12.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 1

shell:
  program: /bin/bash
  args:
    - --login

key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: Insert,    mods: Shift,         action: PasteSelection              }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Equals,    mods: Control,       action: IncreaseFontSize            }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: F11,       mods: None,          action: ToggleFullscreen            }
  - { key: Paste,     mods: None,          action: Paste                       }
  - { key: Copy,      mods: None,          action: Copy                        }
  - { key: PageUp,    mods: None,          action: ScrollPageUp,   mode: ~Alt  }
  - { key: PageDown,  mods: None,          action: ScrollPageDown, mode: ~Alt  }
  - { key: Home,      mods: Shift,         action: ScrollToTop,    mode: ~Alt  }
  - { key: End,       mods: Shift,         action: ScrollToBottom, mode: ~Alt  }
  - { key: A,         mods: Control|Shift, chars: "\x1b[65;5u"                 }
  - { key: B,         mods: Control|Shift, chars: "\x1b[66;5u"                 }
  - { key: F,         mods: Control|Shift, chars: "\x1b[70;5u"                 }
  - { key: H,         mods: Control|Shift, chars: "\x1b[72;5u"                 }
  - { key: J,         mods: Control|Shift, chars: "\x1b[74;5u"                 }
  - { key: L,         mods: Control|Shift, chars: "\x1b[76;5u"                 }
  - { key: P,         mods: Control|Shift, chars: "\x1b[80;5u"                 }
  - { key: T,         mods: Control|Shift, chars: "\x1b[83;5u"                 }
  - { key: T,         mods: Control|Shift, chars: "\x1b[84;5u"                 }

