case $- in                                                          ## If not running interactively, don't do anything.
    *i*) ;;
      *) return;;
esac

set -o vi                                                           # Use VI mode for terminal navigation

HISTCONTROL=ignoreboth                                              # Don't save duplicate lines or lines starting with space in history.
HISTSIZE=1000                                                       # Set history length.
HISTFILESIZE=2000                                                   # Set history file size.

# Shell options.
shopt -s histappend                                                 # Append to the history file, don't overwrite it.
shopt -s checkwinsize                                               # Check the window size; update LINES, COLUMNS.
shopt -s globstar                                                   # Match all files and zero or more directories and subdirectories with "**"

if ! shopt -oq posix; then                                          # Enable programmable completion features.
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
  fi
fi

if [ -x $(which dircolors) ]; then                                  # Enable color support.
    test -r ${HOME}/.dircolors && \
        eval "$(dircolors -b ${HOME}/.dircolors)" || \
        eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if [ -f ${HOME}/.env/config/bash/vars.sh ]; then                                # Source env vars.
  source ${HOME}/.env/config/bash/vars.sh
fi

if [ -f ${ALIASES} ]; then                                          # Source alias definitions.
    source ${ALIASES}
fi

export PATH="$HOME/.local/bin:$PATH"

if [ -x $(which thefuck) ]; then                                    # Enable thefuck.
  eval $(thefuck --alias)
fi

if [ -x $(which wal) ]; then                                        # Enable wal.
  wal -i ~/.env/config/backgrounds/forest.jpg
fi

export EDITOR="vim"

#export $(xargs < ~/Documents/.env)

export PATH="$PYENV_ROOT/bin:$PATH"

eval "$(ssh-agent)"
ssh-add
eval "$(starship init bash)"

xmodmap ~/.xmodmaprc

export GPG_TTY=$(tty)
