case $- in                                                          ## If not running interactively, don't do anything.
    *i*) ;;
      *) return;;
esac

export EDITOR="vim"

set -o vi                                                           # Use VI mode for terminal navigation

HISTCONTROL=ignoreboth                                              # Don't save duplicate lines or lines starting with space in history.
HISTSIZE=1000                                                       # Set history length.
HISTFILESIZE=2000                                                   # Set history file size.

# Shell options.
shopt -s histappend                                                 # Append to the history file, don't overwrite it.
shopt -s checkwinsize                                               # Check the window size; update LINES, COLUMNS.

if ! shopt -oq posix; then                                          # Enable programmable completion features.
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
  fi
fi

if [ -f ${HOME}/.env/config/bash/vars.sh ]; then                                # Source env vars.
  source ${HOME}/.env/config/bash/vars.sh
fi

if [ -f ${ALIASES} ]; then                                          # Source alias definitions.
    source ${ALIASES}
fi

export PATH="$HOME/.local/bin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="/Users/polo/Library/Python/3.9/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


if [ -x $(which wal) ]; then                                        # Enable wal.
    wal -i ${HOME}/.env/config/backgrounds/ppf.png -n
fi


#eval "$(ssh-agent)"
#ssh-add
eval "$(starship init bash)"

#xmodmap ~/.xmodmaprc

#export GPG_TTY=$(tty)
