
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# User configuration
export MANPATH="/usr/local/man:$MANPATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="/Users/polo/Library/Python/3.9/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

export LANG=en_US.UTF-8

#if [[ -n $SSH_CONNECTION ]]; then
#    export EDITOR='vim'
#else
#    export EDITOR='nvim'
#fi

(cat ~/.cache/wal/sequences &)

if [[ -x $(which wal) ]]; then
   if [[ 0 -eq $(cat ${HOME}/.env/config/lightordark) ]]
        then
          wal --backend haishoku -i ${HOME}/.env/config/backgrounds/$(cat ${HOME}/.env/config/bg-image) -n -q 
        else
          wal --backend haishoku -i ${HOME}/.env/config/backgrounds/$(cat ${HOME}/.env/config/bg-image) -n -q  -l
    fi
fi


# Aliases
alias c='clear'
alias h='history'
alias n='nvim'
alias t='tmux'
alias td='tmux detach'
alias tks='tmux kill-server'


#Plugins
plugins=(git zsh-autosuggestions kubectl)
source $ZSH/oh-my-zsh.sh

bindkey -s '^[[1;2P' "~/.env/config/scripts/tmux-project-launch.sh^M" # ctrl f for find project 
bindkey -s '^[[1;2Q' "~/.env/config/scripts/nvim-project-launch.sh $(pwd)^M" # ctrl p to open nvim on file
bindkey -s '^[[1;2T' "~/.env/config/scripts/tmux-session-select.sh^M" # ctrl t to choose a tmux session to attach too
bindkey -s '^[[1;2S' "~/.env/config/scripts/polo-code.sh^M" # ctrl shift 6 to launch a tmux term
bindkey -s '^[[1;2R' "~/.env/config/scripts/launch-terminal.py^M" # ctrl shift 7 to launch ps-code
bindkey -s '^[[1;5R' "~/.env/config/scripts/launch-terminal-no-mux.py^M" # ctrl shift 8 to add non tmux term



#Star Ship
eval "$(starship init zsh)"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi


